package cmd

import (
	"fmt"
	"log"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

var initCmd = &cobra.Command{
	Use:   "init [project-name]",
	Short: "Create a new Shelly script project",
	Long: `Initializes a new spgtty project with all necessary files and directories.

Creates:
  - .spgtty.yaml    Configuration file (set your Shelly IP here)
  - main.js         Entry point with Shelly boilerplate code
  - src/            Directory for modules
  - dist/           Build output directory
  - .gitignore      Ignores dist/ folder

Examples:
  spgtty init                  # Initialize in current directory
  spgtty init my-project       # Create new project directory`,
	Args: cobra.MaximumNArgs(1),
	Run:  initProj,
}

// Template for .spgtty.yaml configuration file
const configTemplate = `# spgtty configuration
# Documentation: https://github.com/GrosseBen/spgtty

# Shelly device settings
shelly:
  host: ""           # IP or hostname of your Shelly device (e.g., "192.168.1.100")
  script_id: 1       # Script slot on the device (1-10)

# Build settings
build:
  entry: "main.js"       # Entry point file
  output: "dist/main.js" # Output file path
  minify: true           # Enable minification (set to false for debugging)
`

// Template for main.js entry point
const mainJsTemplate = `// Shelly Script - generated by spgtty
// Documentation: https://shelly-api-docs.shelly.cloud/gen2/Scripts/
//
// Build: spgtty build
// Upload: spgtty upload --host <your-shelly-ip>

/**
 * Main entry point for your Shelly script.
 * This function is called when the script starts.
 */
function main() {
    print("Hello from Shelly!");
    
    // Example: Get device info
    Shelly.call("Shelly.GetDeviceInfo", {}, function(result, error) {
        if (error) {
            print("Error:", error);
        } else {
            print("Device:", result.name || result.id);
        }
    });
}

// Start the script
main();
`

// Template for .gitignore
const gitignoreTemplate = `# Build output
dist/

# OS files
.DS_Store
Thumbs.db

# IDE/Editor
.vscode/
.idea/
*.swp
*.swo

# Optional: Uncomment to ignore local config (if it contains secrets)
# .spgtty.yaml
`

func initProj(cmd *cobra.Command, args []string) {
	// Determine project directory
	projectDir := "."
	if len(args) > 0 {
		projectDir = args[0]
	}

	// Check if directory already has spgtty files
	if projectDir == "." {
		if _, err := os.Stat(".spgtty.yaml"); err == nil {
			log.Fatal("Project already initialized (.spgtty.yaml exists)")
		}
	}

	// Create project directory if specified
	if projectDir != "." {
		if err := os.MkdirAll(projectDir, 0755); err != nil {
			log.Fatalf("Failed to create project directory: %v", err)
		}
		fmt.Printf("Creating project in %s/\n", projectDir)
	} else {
		fmt.Println("Initializing project in current directory...")
	}

	// Create src/ directory
	srcDir := filepath.Join(projectDir, "src")
	if err := os.MkdirAll(srcDir, 0755); err != nil {
		log.Fatalf("Failed to create src/ directory: %v", err)
	}

	// Create dist/ directory
	distDir := filepath.Join(projectDir, "dist")
	if err := os.MkdirAll(distDir, 0755); err != nil {
		log.Fatalf("Failed to create dist/ directory: %v", err)
	}

	// Write .spgtty.yaml
	configPath := filepath.Join(projectDir, ".spgtty.yaml")
	if err := os.WriteFile(configPath, []byte(configTemplate), 0644); err != nil {
		log.Fatalf("Failed to write .spgtty.yaml: %v", err)
	}

	// Write main.js only if it doesn't exist
	mainPath := filepath.Join(projectDir, "main.js")
	if _, err := os.Stat(mainPath); os.IsNotExist(err) {
		if err := os.WriteFile(mainPath, []byte(mainJsTemplate), 0644); err != nil {
			log.Fatalf("Failed to write main.js: %v", err)
		}
	} else {
		fmt.Println("ℹ️  main.js already exists - preserving your code")
	}

	// Write .gitignore
	gitignorePath := filepath.Join(projectDir, ".gitignore")
	// Only write if it doesn't exist (don't overwrite existing .gitignore)
	if _, err := os.Stat(gitignorePath); os.IsNotExist(err) {
		if err := os.WriteFile(gitignorePath, []byte(gitignoreTemplate), 0644); err != nil {
			log.Fatalf("Failed to write .gitignore: %v", err)
		}
	}

	// Print success message
	fmt.Println()
	fmt.Println("✅ Project initialized!")
	fmt.Println()
	fmt.Println("Created files:")
	fmt.Println("  .spgtty.yaml    - Configuration (set your Shelly IP here)")
	fmt.Println("  main.js         - Entry point")
	fmt.Println("  src/            - Directory for modules")
	fmt.Println("  dist/           - Build output")
	fmt.Println("  .gitignore      - Git ignore rules")
	fmt.Println()
	fmt.Println("Next steps:")
	fmt.Println("  1. Edit .spgtty.yaml and set your Shelly device IP")
	fmt.Println("  2. Write your code in main.js")
	fmt.Println("  3. Run 'spgtty build' to compile")
	fmt.Println("  4. Run 'spgtty upload' to deploy to your Shelly")
	fmt.Println()
}
